# Generated by Django 6.0.5 on 2026-06-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_sessions', '0002_session_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='booking_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='category',
            field=models.CharField(default='Tech', max_length=50),
        ),
        migrations.AddField(
            model_name='session',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='rating',
            field=models.FloatField(default=4.9),
        ),
    ]
